### ISSUE TITLE
doubts about L1 cache configuration

### ISSUE THREAD

**Issue by clx7913** [freechipsproject/rocket-chip#1352]
For example,my L1 cache has the configuration:"NSets=64,NWays=4".How many bytes or bits each way has?Which parameter should I refer to in /coreplex/Configs.scala,the RowBits or the CacheBlockBytes?

**Comment by hcook** [comment]
`CacheBlockBytes` controls the size of each cache block (of which there are ways*sets).

`RowBits` controls the dimensions of the data SRAM.

**Comment by clx7913** [comment]
You mean each way has `CacheBlockBytes` bytes?

If the default value of `CacheBlockBytes` is 64,so the size of the L1 cache is `sets*ways*CacheBlockBytes=64*4*64`.Am I right?

**Comment by hcook** [comment]
It depends what you mean by "each way". Each way of a set is `CacheBlockBytes` of data. Each way of a cache is therefore `CacheBlockBytes*sets`. The default cache size is 16Kb.

**Comment by clx7913** [comment]
Thank you so much!That's really detailed.

**Comment by cabingh** [comment]
Hello I am still learning the source code structures. where I can find this default CacheBlockBytes setting? I don't see  /coreplex/Configs.scala in current src/main/scala. Thanks in advance.

**Comment by aignacio** [comment]
@cabingh I'm not sure about that but [check this line](https://github.com/freechipsproject/rocket-chip/blob/05ccbffaa926cc157665b02c7e0d56f4c4186e14/src/main/scala/subsystem/MemoryBus.scala#L13) where it's defined as 64 bytes. As an example, the configuration of **L1** for **TinyCore** (If I'm right) it's:
D$ cache = 256 **nSets** * 1 **nWays** * 64 **CacheBlockbytes** = 16384 Bytes = **16 kiB**
I$ cache = 64 **nSets** * 1 **nWays** * 64 **CacheBlockbytes** = 4096 Bytes = **4 kiB**
...using the image below (different cfg) we can say that by default we have block size equals to 512 bits instead of 32-bit like image.
![screenshot from 2018-11-15 14-30-45](https://user-images.githubusercontent.com/5991372/48568432-88338500-e8e6-11e8-83db-21a8350a5e81.png)
is this right @aswaterman ?

**Comment by aswaterman** [comment]
@aignacio that sounds correct to me.

**Comment by jerryhethatday** [comment]
> `CacheBlockBytes` controls the size of each cache block (of which there are ways*sets).
> 
> `RowBits` controls the dimensions of the data SRAM.

can you further explain the rowbits field, I have no idea what's that for? what does dimensions of the data SRAM mean?

**Comment by aswaterman** [comment]
How wide the data SRAM physically is.  For example, if RowBits is 128 and CacheBlockBytes is 64 (=512 bits), then each cache line spans 4 rows.

It's essentially a physical-design tuning parameter.
