### ISSUE TITLE
Parameterization issues

### ISSUE THREAD

**Issue by gthompsonx** [freechipsproject/rocket-chip#901]
I'm trying to change configs of the rocket-chip, but finding it very unclear which knobs to use when.

For example:

How do I control how many processors are in the system?
How can I remove the L1 caches?
How can I remove the L2 cache?

Thanks,
Greg

**Comment by ben-k** [comment]
These types of options are controlled by defining different configs and then setting the CONFIG variable at the command line when building the design.  Some predefined configs can be found in `src/main/scala/system/Configs.scala`.

> How do I control how many processors are in the system?

There are pre-existing hooks for this (`WithNBigCores`, `WithNSmallCores`, `WithNTinyCores`).  To build a dual-core design:

```
class MyCustomConfig extends Config(new WithNBigCores(2) ++ new BaseConfig)
```

> How can I remove the L1 caches?

This is [not supported](https://github.com/freechipsproject/rocket-chip/blob/master/src/main/scala/tile/RocketTile.scala#L22).  If you use `TinyConfig`, the design will have a data scratchpad instead of a data cache.

> How can I remove the L2 cache?

There's no L2 cache in this repo.  So I guess it's already done for you!

Once you've defined your custom config in Chisel, you can build it by running the usual steps and setting the CONFIG variable:

```
make CONFIG=MyCustomConfig
```

**Comment by gthompsonx** [comment]
Thanks!
